# Generated by Django 3.2.4 on 2021-06-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesurement', '0002_rename_mesurements_mesurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesurement',
            name='date',
        ),
    ]
