# Generated by Django 3.2.4 on 2021-06-18 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mesurement', '0003_remove_mesurement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendation',
            name='date',
        ),
        migrations.AddField(
            model_name='recomendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
