# Generated by Django 3.2.4 on 2021-06-18 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{3}-\\d{2}$')]),
        ),
    ]
