# Generated by Django 3.2.4 on 2021-06-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='saturation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='type',
            field=models.CharField(default='Load', max_length=255),
            preserve_default=False,
        ),
    ]
